// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	openInput: (id: string) => __TAURI_INVOKE<null>("plugin:midi|open_input", { id }),
	closeInput: (id: string) => __TAURI_INVOKE<void>("plugin:midi|close_input", { id }),
	openOutput: (id: string) => __TAURI_INVOKE<null>("plugin:midi|open_output", { id }),
	closeOutput: (id: string) => __TAURI_INVOKE<void>("plugin:midi|close_output", { id }),
	outputSend: (id: string, msg: number[], timestamp: string | null) => __TAURI_INVOKE<null>("plugin:midi|output_send", { id, msg, timestamp }),
};

/** Events */
export const events = {
	midiMessage: makeEvent<MIDIMessage>("plugin:midi:midi-message"),
	stateChange: makeEvent<StateChange>("plugin:midi:state-change"),
};

/* Types */
export type MIDIMessage = [string, string, number[]];

export type StateChange = {
	inputs: ([string, string])[],
	outputs: ([string, string])[],
};

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: ((payload: T) => target.emit(name, payload) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

